[[redirects]]
  from = "/producto"
  to = "https://github.com/MiyerGonzalez/alurageek/db.json"
  status = 200
  force = true
  headers = {X-From = "Netlify"}
[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"